### PR TITLE
docs: setting up dev containers

### PR DESCRIPTION
**Pull request by ThEditor**
## Summary

- Enabled `sphinx.ext.autosectionlabel` to link sections
- Mentioned the two ways of dev environment setup - host, devcontainers.
- Created a guide on setting up devcontainers

## Reviewer guidance

Build the docs using `make docs` and open `localhost:8888` to check the updated documentation.

----

## Testing checklist

- [x] Contributor has fully tested the PR manually
- [ ] If there are any front-end changes, before/after screenshots are included
- [ ] Critical user journeys are covered by Gherkin stories
- [ ] Critical and brittle code paths are covered by unit tests

## PR process

- [ ] PR has the correct target branch and milestone
- [ ] PR has 'needs review' or 'work-in-progress' label
- [ ] If PR is ready for review, a reviewer has been added. (Don't use 'Assignees')
- [ ] If this is an important user-facing change, PR or related issue has a 'changelog' label
- [ ] If this includes an internal dependency change, a link to the diff is provided

## Reviewer checklist

- Automated test coverage is satisfactory
- PR is fully functional
- PR has been tested for [accessibility regressions](http://kolibri-dev.readthedocs.io/en/develop/manual_testing.html#accessibility-a11y-testing)
- External dependency files were updated if necessary (`yarn` and `pip`)
- Documentation is updated
- Contributor is in AUTHORS.md

### CODE REVIEW

**Comment by vkWeb** [comment]
@ThEditor this is marked as draft, is it ready for review or you are gonna be making more changes?

**Comment by ThEditor** [comment]
Woops, forgot to mark it ready for review.

**Comment by vkWeb** [comment]
I appreciate your thought process about keeping the old docker instructions and marking it as legacy. Overall nice work.

I'll make further edits on top of your documentation and I will soon let you know about the final product.

@ThEditor merged your PR, thanks man!

**Comment by vkWeb** [comment]
I have edits on top of your docs here -- https://github.com/learningequality/kolibri/pull/11443.

**Pull request merged**
